<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title><?= $title ?? 'Eisenhower Tasks' ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/assets/css/style.css">
</head>
<body>

<?php require '/header.php'; ?>

<main class="container">
    <?= $content ?>
</main>

<?php require '/footer.php'; ?>

</body>
</html>
